# Generated by Django 5.1 on 2024-10-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_alter_job_remote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='remote_type',
        ),
    ]
