# Generated by Django 5.1 on 2024-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_remove_job_remote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='onsite', max_length=10),
        ),
    ]
