# Generated by Django 5.0.4 on 2024-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('BUDGET', 'BUDGET')], max_length=100, null=True),
        ),
    ]
