# Generated by Django 5.0.4 on 2024-08-15 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_alter_vehicle_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('ESEWA', 'ESEWA'), ('CARD', 'CARD'), ('OTHER', 'OTHER')], max_length=100)),
                ('cancel_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicle')),
            ],
        ),
    ]
