# Generated by Django 5.0.4 on 2024-08-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_week',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image_back',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image_front',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image_left',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image_right',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image_speedometer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle'),
        ),
        migrations.CreateModel(
            name='BookingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image_front', models.ImageField(blank=True, null=True, upload_to='vehicle')),
                ('vehicle_image_back', models.ImageField(blank=True, null=True, upload_to='vehicle')),
                ('vehicle_image_left', models.ImageField(blank=True, null=True, upload_to='vehicle')),
                ('vehicle_image_right', models.ImageField(blank=True, null=True, upload_to='vehicle')),
                ('vehicle_image_speedometer', models.ImageField(blank=True, null=True, upload_to='vehicle')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle_management.booking')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.ManyToManyField(blank=True, null=True, to='vehicle_management.price'),
        ),
    ]
