# Generated by Django 5.0.4 on 2024-08-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0004_price_remove_vehicle_price_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.ManyToManyField(to='vehicle_management.price'),
        ),
    ]
