# Generated by Django 5.0.4 on 2024-08-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0005_alter_vehicle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.ManyToManyField(related_name='vehicles', to='vehicle_management.price'),
        ),
    ]
