# Generated by Django 5.0.4 on 2024-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0006_alter_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_verified',
            field=models.BooleanField(default=False),
        ),
    ]
