# Generated by Django 5.0.4 on 2024-08-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0007_booking_user_verified_booking_vendor_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='vehicle_management.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='bike_condition',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True),
        ),
    ]
