# Generated by Django 5.0.4 on 2024-08-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0008_remove_vehicle_price_price_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='vehicle_management.vehicle'),
        ),
    ]
