# Generated by Django 5.1 on 2024-08-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0011_canclebooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancleBooking',
            new_name='CancelBooking',
        ),
    ]
