# Generated by Django 5.0.4 on 2024-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0014_vehicle_date_of_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-date_of_upload']},
        ),
    ]
