# Generated by Django 5.1 on 2024-09-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0015_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'BIKE'), ('SCOOTER', 'SCOOTER'), ('ELETRIC', 'ELETRIC'), ('CAB', 'CAB')], max_length=100),
        ),
    ]
