# Generated by Django 5.1 on 2024-11-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0020_vehicle_chassis_number_vehicle_engine_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
