# Generated by Django 5.1 on 2024-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0022_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('ELECTRIC', 'ELECTRIC')], default='PETROL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('BUDGET', 'BUDGET'), ('PREMIUM', 'PREMIUM'), ('ELECTRIC', 'ELECTRIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'BIKE'), ('SCOOTER', 'SCOOTER'), ('ELECTRIC', 'ELECTRIC'), ('CAB', 'CAB')], max_length=100),
        ),
    ]
