# Generated by Django 5.1 on 2024-11-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0025_alter_promocode_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.promocode'),
        ),
    ]
