# Generated by Django 5.0.4 on 2024-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='citizenship_back',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='citizenship_front',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='driving_license',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='issued_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driving_license_back',
            field=models.ImageField(blank=True, null=True, upload_to='driving_license'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driving_license_front',
            field=models.ImageField(blank=True, null=True, upload_to='driving_license'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='issued_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_registration',
            field=models.ImageField(blank=True, null=True, upload_to='company_registration'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='registered_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
