# Generated by Django 5.0.4 on 2024-08-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_citizenship_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship'),
        ),
    ]
