# Generated by Django 5.1 on 2024-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_image_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image_left',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image_right',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image_top',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_no_image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vat_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vat_no_image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
