# Generated by Django 5.1 on 2024-09-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userprofile_user_image_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='pan_no_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan_no'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vat_no_image',
            field=models.ImageField(blank=True, null=True, upload_to='vat_no'),
        ),
    ]
