# Generated by Django 5.1 on 2024-11-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='driving_license_back',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image_bottom',
        ),
    ]
