# Generated by Django 5.1 on 2024-11-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userprofile_driving_license_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='driving_license_back',
        ),
    ]
