# Generated by Django 5.1 on 2024-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_userprofile_driving_license_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='driving_license_back',
            field=models.ImageField(blank=True, null=True, upload_to='driving_license'),
        ),
    ]
